### ISSUE TITLE
Clarify Java version

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#12]
I'm unsure about the Java version constraints of the plugin. This is what I see:
* classpath files require a Java 1.8 JRE
* pom.xml files say nothing about Java level
* Java code uses raw types (Java 1.5) at some places.

Can we assume Java 1.8 as minimum requirement everywhere (or is there some outside constraint, e.g. by the checkstyle upstream project, or by some used library)? In that case, I would want to
* add this to the parent POM
* add this to the /.settings/jdt.core.prefs of every project
* convert the raw types to generics in the Java sources

**Comment by lkoe** [comment]
Yes, 1.8 is the minimum requirement, as it is required by Checkstyle core.
AFAIK Tycho applies the Java version requirement from the bundle manifests (`Bundle-RequiredExecutionEnvironment: JavaSE-1.8`), so it's superficial to restate in the POM (I think).

>Java code uses raw types (Java 1.5) at some places.

Yes, thats because the codebase originates largely from 2005/2006 and I didn't feel motivated enough to adapt all of it. On top I think there are still alot of Eclipse API which don't support generics.
