### ISSUE TITLE
https://checkstyle.org/eclipse-cs/update is broken

### ISSUE THREAD

**Issue by rjonna** [checkstyle/eclipse-cs#128]

**Comment by rnveach** [comment]
@rjonna What do you mean by broken? What is the issue?

**Comment by rjonna** [comment]
I cannot install the plugin. The url returns 404.

![image](https://user-images.githubusercontent.com/3530174/51266589-86cb1b00-1970-11e9-8036-86276a5748f9.png)

**Comment by rnveach** [comment]
@rjonna 
> https://github.com/checkstyle/checkstyle.github.io .

The install website at https://checkstyle.org/eclipse-cs/#!/install says the update site is https://checkstyle.org/eclipse-cs/update and that is showing plugin information in `Install New Software` in eclipse.

**Comment by hcientist** [comment]
@rnveach https://www.isitdownrightnow.com/checkstyle.org.html (404)

**Comment by rjonna** [comment]
@rnveach - Even the content.xml file that Eclipse needs is also missing. Please try the url from the screenshot I posted above. Even that gives 404. Not sure if others are able to install.

**Comment by hcientist** [comment]
we are also experiencing issues with several students here being unable to install directly, instead grabbing the previous version zip manually and installing from the "local site" is working for now

**Comment by rnveach** [comment]
@romani @lkoe Can either of you comment on update site and where it is located?

**Comment by lkoe** [comment]
The binaries for the update site are located on bintray (https://bintray.com/eclipse-cs/eclipse-cs/update-site#files)

The website on github pages - which provides the update site URL - only contains a few descriptor files, which reference the bintray location:
http://checkstyle.org/eclipse-cs/update/p2.index
http://checkstyle.org/eclipse-cs/update/compositeArtifacts.xml
http://checkstyle.org/eclipse-cs/update/compositeContent.xml

Visiting the update site URL (https://checkstyle.org/eclipse-cs/update) in a browser always results in a 404, because thats no website content. This has no effect on the update site functionality for eclipse.

Installation problems can occur when either Github pages or Bintray is not available. It's hard to say in retrospect, which was the case.

I've just tested installation via update site and eclipse marketplace for the newest version (8.18).
Please reopen if your issues are not resolved.

**Comment by Bananeweizen** [comment]
The root cause for not being update to install plugins hosted on bintray is almost always a problem on the *user* side. The certifacate used by bintray is not contained in the certificate store file of old Java installations, therefore http*s* to bintray fails. Install a more recent JDK, or copy the "cacerts" from a recent JDK11 to your existing JDK.
