### ISSUE TITLE
Milestones still open and releases not promoted

### ISSUE THREAD

**Issue by eric-milles** [checkstyle/eclipse-cs#143]
A few housekeeping requests:
1. Could the milestones be closed?  They all refer to past releases?
1. Could the releases be promoted in github?  It still shows 8.10 as the latest release on the [Releases](https://github.com/checkstyle/eclipse-cs/releases) tab.
1. Is it possible to include past releases on the update site or make update site archives available?  8.18 has breaking changes once again and I can't direct my developers to 8.17 since it is not available through the update site and the release on github only includes the source.

**Comment by rnveach** [comment]
@lkoe Can you respond about point 3?
@romani Do you know how to promote a release?

I deleted the old milestones and created a new one with just the same information as main project.

**Comment by lkoe** [comment]
1. sure, although it's currently not particularly useful , due to rare project activity
2. afaik github uses git tags for the release info. The tags are there but missing additional information. In any case, binaries aren't hosted on github, so it't pretty much useless too
3. All update sites are hosted on bintray (https://dl.bintray.com/eclipse-cs/eclipse-cs/), older versions can be installed using the specific update site for that version, for instance https://dl.bintray.com/eclipse-cs/eclipse-cs/8.17.0/

The official main update site and eclipse marketplace always point to the newest version, of course.

**Comment by eric-milles** [comment]
Thanks for instructions on installing previous release.  I was able to install 8.17 with no trouble.

To promote a release, go to Code tab of project in Github, then Releases sub-tab.  Click "Draft a new release" and type in the tag name for one of the releases, like "8.10.1".  You can add more details, but the tag name is enough to have GitHub recognize it as a release.  Repeat for each of the 8 remaining tags.

**Comment by rnveach** [comment]
I have promoted all tags to releases. I didn't add any additional information to them.
Thanks for the instructions.

Installing older versions was added to the readme.

This should cover everything, so I am closing this issue.
