### ISSUE TITLE
Check plugin support in Eclipse 2020-03 (4.15)

### ISSUE THREAD

**Issue by romani** [checkstyle/eclipse-cs#205]
This is to inform you that your Eclipse Marketplace Listing Checkstyle
Plug-in has been automatically updated to indicate that it is now supporting
the latest Eclipse release (2020-03 (4.15)).

If your listing does not support the latest Eclipse release, please revise
its list of Eclipse Supported Releases using the following url:

https://marketplace.eclipse.org/node/150/edit

**Comment by romani** [comment]
@Bananeweizen , @Calixte , I got this a email notification, please recheck this when you have a time.

**Comment by Bananeweizen** [comment]
I always use the milestone builds of the next Eclipse version for my development, since I'm also Eclipse platform committer and want to see regressions early. Therefore I should typically notice if a plugin like eclipse-cs doesn't work anymore. That's not as good as having automated tests running against a matrix of Eclipse versions, but it seems fine to me to always let the marketplace listing be upgraded to say it's compatible with the next release.
