### ISSUE TITLE
Automate metadata verification using reflection

### ISSUE THREAD

**Issue by rnveach** [checkstyle/eclipse-cs#3]
As discussed at https://sourceforge.net/p/eclipse-cs/discussion/274376/thread/3b44a5eb/# , we should implement sevntu's metadata verification to make updates to the metadata easier.
This will ensure updates aren't missed and that the meta file is defined correctly.

**Comment by rnveach** [comment]
@lkoe I will help out with this but I am very new to eclipse-cs's code.
I want to put a junit inside https://github.com/checkstyle/eclipse-cs/tree/master/net.sf.eclipsecs.checkstyle but the current folder doesn't even have a `src` folder.

Can you guide me on how you want tests inside this project?
If you go as far as starting a branch with an empty junit test, I can go from there.

**Comment by romani** [comment]
existed discussions (2014 year): https://groups.google.com/forum/#!searchin/checkstyle-devel/Metadata$20information$20in$20Checkstyle$27s$20Check%7Csort:date/checkstyle-devel/UeboJR0evSU/bialYabqNyIJ

**Comment by rnveach** [comment]
@lkoe Thank you for the branch. I have the test working at https://github.com/rnveach/eclipse-cs/commits/issue_3 with some fixes.

I have a question so far:
For `ConstantNameCheck` what is the reason for 2 names: https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/naming/checkstyle-metadata.xml#L34-L35
The check is only located in `naming` package.
Is the other one for some type of backward compatibility? Is it still needed and can't be removed even though it doesn't exist there anymore?

**Comment by lkoe** [comment]
@rnveach ah, you found it already, I was jsut about to tell you :-) Great stuff!

1) The reason is that this check had been in the other package before it was moved to `naming` somewhere like 10 years ago. It was indeed used for backwards compatibility, but can be safely removed now.

2) Some checkstyle violations can be "quickfixed" inside Eclipse via quickfix implementations provided by eclipse-cs. The `quickfix` element is for assigning quickfixes to the modules producing those fixable violations.

**Comment by lkoe** [comment]
one caveat for unit testing inside eclipse:
The Eclipse Maven integration/Tycho is pretty stubborn and removes the `test` folder and the JUnit-Library-Container from the project buildpath when the project configuration is updated from the POM. In this case you'd need to manually re-add them. I didn't find a solution for this problem quickly.

The maven build should be fine, at least when run from the root directory. Building single sub-projects might not work due to some strange issue with Tycho.

Tycho is a Maven extension to run Eclipse PDE builds in Maven, essentially. It is mostly driven by the PDE files information (e.g. MANIFEST.MF, build.properties). This is also why 3rd-party dependencies are not declared in the POM as one would expect, but are hosted as binaries inside the projects. There might be some way to do this differently but I don't know it currently.

**Comment by rnveach** [comment]
@lkoe Unit test is passing now. All checks and properties were assigned.
Only thing missing from the update right now are the actual descriptions, instead of `TODO`.
There are some things missing that I thought sevntu had. Test isn't validating basic types, tokens, or quick fix.
Test doesn't validate default values because this was just merged into main project at https://github.com/checkstyle/checkstyle/pull/5402 and will take probably a release to trickle down to this project.

> Tycho 

I am unable to help as I am not familar with eclipse plugin make up.
I have seen other projects create a whole new project just for tests. Example: https://github.com/eclipse/egit-github, if that helps any.
