### ISSUE TITLE
Make used checkstyle version configurable (and per project)

### ISSUE THREAD

**Issue by elmuerte** [checkstyle/eclipse-cs#312]
With breaking changes being made to the configuration file (like https://github.com/checkstyle/checkstyle/issues/7417 ) this plugin can effectively no longer be used when two projects use configuration files which are not compatible with the one specific version this plugin ships with.

**Comment by Bananeweizen** [comment]
We will not be able to change the way this works, because the Eclipse plugin needs to be able to load the main Checkstyle classes correctly. Since there are breaking changes all the time, supporting ranges is way too much effort. Generally speaking, it's recommended to have a separate Eclipse installation per project anyway (not just different workspaces for one single installation). Otherwise you will end with an Eclipse installation that has too many plugins, with conflicting dependencies etc. I run more than 50 Eclipse installations on my system and the additional disk space usage is neglectible.
