### ISSUE TITLE
"Additional Properties..." button in CheckConfigurationPropertiesDialog opens invisible ResolvablePropertiesDialog

### ISSUE THREAD

**Issue by Treehopper** [checkstyle/eclipse-cs#324]
I first thought Eclipse is stuck in some kind of feedback loop, but using flight recorder, I realized there must be an open modal dialog.
I was able to confirm with: Alt+Shift+F1 that the active shell is `ResolvablePropertiesDialog` [1], but as a user I still have no way to use it, other than closing it using Alt+F4.

[1] https://github.com/checkstyle/eclipse-cs/blob/master/net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/ResolvablePropertiesDialog.java

I already had this issue in the past, but currently I am reproducing it with:

- Eclipse Checkstyle: 8.44.0.202108061901
- Version: 4.12.0.RELEASE
- Build Id: 202109130635
- Java: jdk-11.0.5.10-hotspot
- Windows

**Comment by Bananeweizen** [comment]
I can't reproduce this in a current version (also on Windows). The sources look good, there is an initial size set for the dialog etc.
The symptoms you describe would fit to using the wrong shell as parent when opening the dialog. That means code taking "PlatformUI.getWorkbench().getActiveWorkbenchWindow().getShell()" instead of whateverWindowMyParentIs.getShell() when opening a new dialog. I have fixed that pattern in many different plugins, and that may or may not include EclipseCS.
