### ISSUE TITLE
Need new maintainer?

### ISSUE THREAD

**Issue by vtintillier** [checkstyle/eclipse-cs#365]
Hello @romani ,

as mentioned in #364 already, @Calixte had no GitHub activity since May 1st with https://github.com/checkstyle/eclipse-cs-update-site/commit/515038931f10fb9869625583a68e80337c0f1ef9

Maybe that would be a good time for new maintainers to be added to the checkstyle/eclipse-cs and checkstyle/eclipse-cs-update-site repositories to keep this project alive?

That's something I could do, and I also see e.g. @Bananeweizen who has a few opened PR, who might be interested as well?

Thanks for your help

**Comment by romani** [comment]
> That's something I could do

we always welcome new people to project. Please try to fix few issues to understand how project works.

I connected with @Calixte  by email, he responded (7 days ago) that he might have time to do releases this week.
But your involvement is always welcome and as you get some experience in the project we are ok to grant you permissions to release project. Please join a team by starting of contribution.

**Comment by Bananeweizen** [comment]
While I don't have much time myself for contributions, I must admit it _feels_ worse since the Eclipse plugin joined the main checkstyle project. The reviewers of the main checkstyle project typically don't know the Eclipse API, therefore they can't really judge new PRs, which then tend to be open very long (and I don't want to blame the people reviewing the changes, I'm rather looking at the process as such). In the former eclipse-cs setup, I would just merge all my open PRs with when no reviews came in after some days. If we could somehow improve that process, contributions to the Eclipse part would become both easier (I previously could not finish other improvements that depend on open PRs) and more attractive to new contributors.
Any thoughts by others on that?

**Comment by rnveach** [comment]
I can only speak for myself.

I agree, I don't know the Eclipse API and can only really judge code style and things that stand out to us as questionable and in some rare cases, wrong. I have tried to do my own PRs but then some were reverted as wrong and even then I never got a clear picture of why it was wrong.

I am ok with changes, but I am unclear on what you are suggesting? Based on your comment, you want to merge your own works and take control of old PRs? I see no issue with the later, checkstyle maintainers do this too when things are becoming abandoned. For merging, I have no been active in this repo because of my lack of knowledge. But if it makes things to easier to just merge faster, then if you are ready for something to be merged, I would say ping and assign me and I will give a quick glance and approve/merge if nothing stands out to move along the process if that is what we want.

**Comment by romani** [comment]
>must admit it feels worse since the Eclipse plugin joined the main checkstyle project.

Lack of time is unavoidable problem. Can be  resolved only by increasing number of maintainers.

>The reviewers of the main checkstyle project typically don't know the Eclipse API, therefore they can't really judge new PRs

Yes, we need maintainers that can be more plugin specific. In main library project we have so much activities in PRs, that there is no time for plugins left. 

>which then tend to be open very long

Yes, :(. In main library repo we have the same problem. The more complicated update the more likely it will stuck. In plugin repo we can do brief review, but we usually wait for plugin maintainer to do final review and here we have problem, it is where PR is stuck.

>I would just merge all my open PRs with when no reviews came in after some days.

I afraid of this approach, I would rather make it clear that we lost connection to maintainer  and let some others to backup. But it needs pinning from author of PR and it might require more details to share to prove that it works. Still extra activity from PR author is required.
Please rebase all your PRs, share prove of testing and we will merge. But please keep pinning us, sorry we have a lot activities from others.

And we will need to do releases. We need help on this also. Release is very automated already, but still needs some human actions. We can grant some permissions if required.

I just tried to not change assignment from previous maintainer

**Comment by Calixte** [comment]
> If we could somehow improve that process

I am not sure that the existing process was ever clear to me, maybe because I never contributed to the main checkstyle project. I don't feel like I am "the" maintainer of the project. I'm merely pushing updates when I have time. I have no Eclipse PDE, Tycho, OSGi experience besides my tinkering with this project, not much time to grow it, and therefore don't really feel like I'm much use reviewing some of the PRs here.
I can look for obvious mistakes and comment "lgtm" if that helps.
Let's take #355 for example. What's the next step? Is it my responsibility to merge it? Is it just waiting for a formal approval?

**Comment by romani** [comment]
Yes, it would be awesome for you to be aweare of this change, you knows project better than anybody :) of active maintainers.

If you have no problems - just merge such change.

If you need suggestions from me  or anyone  just mention us. We are around, but we will not merge without you. 
You can approve and assign to me or rnveach for second review ad final merge.

**Comment by vtintillier** [comment]
Hi @romani ,
Initially I was more thinking about being sure the plugin releases follow the Checkstyle library closely, but looks like this has been taken care of. But sure I can help with reviews 😃 

(should I close this issue by the way? Calixte is back, and Michael was able to merge quite a few changes already)
