### ISSUE TITLE
Broken translation

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#433]
![grafik](https://user-images.githubusercontent.com/406876/207155085-64462c02-0f62-4295-a558-7515bc54a5a7.png)

When fixing this, the PDE project property for checking localization strings should be enabled, such that those errors are avoided in the future due to validation.

**Comment by rnveach** [comment]
The `%CheckstyleTransformingTooltip` text can be found at
https://github.com/checkstyle/eclipse-cs/blob/dd602eb158f940803f702bb6c19d9d5ed206b9a1/net.sf.eclipsecs.ui/plugin.xml#L415

There is a commented out version at https://github.com/checkstyle/eclipse-cs/blob/dd602eb158f940803f702bb6c19d9d5ed206b9a1/net.sf.eclipsecs.ui/plugin.xml#L443 .

It looks like the missing text should be in https://github.com/checkstyle/eclipse-cs/blob/dd602eb158f940803f702bb6c19d9d5ed206b9a1/net.sf.eclipsecs.ui/plugin.properties based on other labels.

I did not find anything in the history of the file for the expected text of `%CheckstyleTransformingTooltip`. The code was added in 4c2d1bacf4971f8dc456c591f0f51963b862d8b7 and it seems like `%CheckstyleTransformingTooltip` may have been used accidentally instead of `%CheckstyleTransformingAction`. There is a class `CheckstyleTransformingAction` but not `CheckstyleTransformingTooltip`.

Since all these are in separated files with other data, I am not seeing an easy way to build a test to ensure we give all these labels a string.
