### ISSUE TITLE
Development environnement issues with Apple M1

### ISSUE THREAD

**Issue by Calixte** [checkstyle/eclipse-cs#461]
I'm unable to work on the plugin with my M1 mac.
I get the following error in CheckstyleMarkerImageProvider.java
> The type org.eclipse.swt.graphics.Image cannot be resolved. It is indirectly referenced from required type

I sometimes see the error when running `mvn install` as well but haven't been able to reproduce consistently. 

Architecture is arm64 or aarch64. 
I played with the tycho target platform configuration but haven't been able to get it to work yet.

**Comment by romani** [comment]
Please try to compile on old version of plugin, in case it is recent some updates.

Please share whole log of terminal build

**Comment by Bananeweizen** [comment]
The target platform of EclipseCS (which is 2020-09) is not M1 compatible. Create a copy of the ...partial.eclipse.tpd which points to Eclipse 2021-06 or newer: https://www.eclipse.org/eclipse/news/4.20/platform.php#eclipse-mac-aarch64. Then generate a target from the tpd, and include it in a copy of the top level target file. You can use that newer target platform locally during development and everything should work fine.

**Comment by Calixte** [comment]
This seems to work, thank you. What about when I perform the release?
Should we just update the oldest supported Eclipse version to 2021-06?

**Comment by Bananeweizen** [comment]
The release activities are unaffected. The target platform does not become an artifact of the release itself. And the CI server has proven that everything works also with the older general TP.

Whether to upgrade is a tough question generally. I always like supporting as many different and old versions as possible, when I write libraries and apps, since there are always some users still running the oldest platform one can imagine. On the other hand, this comes at increased development effort because of variations between the different versions (and because of unexpected support requests for very old stuff). And it also leads to users being less encouraged to upgrade, which is becoming a security problem more and more over the last years. Think of log4j and similar.
2021-06 is almost 2 years old, so I think it would be fine to increase the minimum version.
