### ISSUE TITLE
Add Module ID to Properties for Checkstyle Problem

### ISSUE THREAD

**Issue by rnveach** [checkstyle/eclipse-cs#468]
![image](https://user-images.githubusercontent.com/5427943/216512047-6a791eb1-051b-421b-aa79-83f1c673eecf.png)

If module has an ID we should display it in this dialog so user can add suppression by ID.

**Comment by profhenry** [comment]
I think it *is* currently already possible to display the module ID.

You need to enable "Include module id (if available) in violation messages"

![Checkstyle2](https://github.com/checkstyle/eclipse-cs/assets/4500024/ee329133-7881-4b4c-a2e6-24e50459c946)

The module ID then appears in the violation message (systemOut) in the following screenshot

![Checkstyle](https://github.com/checkstyle/eclipse-cs/assets/4500024/e38d1715-3f7a-4994-b549-532cfd566568)

This might not be pretty but the module ID is displayed.
The java class name in the violation message in only displayed in case "include rule names in violation messages" is enabled.

But what i am missing is the option to display the module name in the in the violation message because in case there is no module ID set then the module name is required for the suppression.

A workaround might be to set the module ID to the module name for every configured rule.

**Comment by Bananeweizen** [comment]
I'm all fine with adding more fields to the properties dialog. Especially for regex based checks I run into the same issue all the time. 

However, a while ago I was wondering if it wouldn't be even more useful to provide "create exclusion" via a quickfix, instead of letting the user create it from the fields that he can read there. I'm just not certain how many different variants might be possible, and how to query those variants nicely from the user (e.g. do you want to suppress all checks of this type, or just the check with this id? for the affected file only, for all files, for all files with the same name, ...?)
