### ISSUE TITLE
patch for sevntu is created for each module

### ISSUE THREAD

**Issue by Bananeweizen** [checkstyle/eclipse-cs#616]
The patch creation for the sevntu checks is executed once per module. That will be more visible once #615 is merged. That's not really necessary, or is @rnveach ? To my understanding the patch is created for the complete repository, independent of the modules. I guess that it would be okay if I change the build to only create that patch once, in an arbitrary module (which could be done via a maven profile with a file existence condition).

**Comment by rnveach** [comment]
I assume you mean maven sub-modules. When I read this, I started assuming you meant Checkstyle modules, which sounds impossible unless it was patch-filters (which reads the config) is doing this.

Since we run `exec-maven-plugin`, I assume you are right that we run it for every sub-module. You should be able to confirm if `outputFile` is made unique for each run.

> the patch is created for the complete repository

Correct, complete git repository and everything cataloged by it.

> it would be okay if I change the build to only create that patch once, in an arbitrary module 

This sounds reasonable to me, but the file location would have to be the same for all modules. Last I heard, maven-checkstyle-plugin has this similar issue where it can't have a config be in the same location for all sub-modules without using a full hardcoded path as each module has a different relative file path.
