### ISSUE TITLE
Can't install plugin in eclipse photon

### ISSUE THREAD

**Issue by jschewebbn** [checkstyle/eclipse-cs#86]
Following the instructions at https://checkstyle.org/eclipse-cs/#!/install yields
```
Unable to read repository at https://checkstyle.github.io/eclipse-cs/update/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Going to the page directly yields a 404.

**Comment by lkoe** [comment]
Please check if you're using a current Java version (latest fixpack). Typically these type of errors occur, when the JVMs truststore contains outdated root certificates.

**Comment by jschewebbn** [comment]
I just updated to the latest version, shutdown eclipse, started eclipse, went to the marketplace to install eclipse-cs and still the same error.
```
>java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

Going to https://checkstyle.github.io/eclipse-cs/update/content.xml in a browser gives me a 404 message.

**Comment by lkoe** [comment]
I just tested it on Eclipse Photon and it worked alright for me, even with a bit of an older jdk

```
java.runtime.version=1.8.0_151-b12
```
I did:
Help->Install new software->Work with: https://checkstyle.github.io/eclipse-cs/update/

https://checkstyle.github.io/eclipse-cs/update/content.xml will not do anything, because such a resource does not exist (there). But this does: https://checkstyle.org/eclipse-cs/update/compositeContent.xml

Please check in Help->About->Installation details->Configuration whether the JRE you listed above is actually being used by Eclipse.

**Comment by jschewebbn** [comment]
It seems that just installing the new version of Java wasn't enough. I needed to go into the Eclipse application settings and change the Java version used.

**Comment by avinashpingle** [comment]
Updating Java solved my problem

**Comment by rnveach** [comment]
>  I needed to go into the Eclipse application settings and change the Java version used.

You can change the default java version used by eclipse by changing the `eclipse.ini` file.
Add/change the option `-vm` to specify the path directly to your `javaw.exe` inside the JDK.
Example: `-vm D:/Program Files/JDK8/bin/javaw.exe`
